"""The script a training run is, written out so it can be read and re-run.

Clicking Train in the UI does something specific, and until now the only way
to find out what was to read the source. That is the wrong way round: the
person choosing between five algorithms is exactly the person who needs to
see what each one will do, and "trust me" is not an answer when the output is
a model that will be filling in other people's claims forms.

So a run hands back two things besides the model. The **recipe** is the
algorithm's own account of its steps, in order, in words - it lives beside
each algorithm rather than here, because the algorithm is the only thing that
knows. The **script** is this module: real Python, no placeholders, that
does what the run just did using nothing but the public API. Save it, run it,
get the same model - the seed is written into it for exactly that reason.

It is generated rather than kept as a template file because every line of it
has to stay true. A script with a parameter the UI no longer sends is worse
than no script, and the only way to be sure is to build it from the same
options object the run was given.
"""

from __future__ import annotations

import json
from typing import Any

from ..schema import FormSchema
from . import algos
from .model import TrainOptions


def _literal(value: Any) -> str:
    return json.dumps(value) if not isinstance(value, str) else repr(value)


def recipe(options: TrainOptions) -> list[str]:
    """What the chosen algorithm does, step by step, in its own words."""
    return list(algos.get(options.algorithm).recipe)


def command(options: TrainOptions, schema_path: str = "form.schema.json",
            records_path: str = "records.json",
            model_path: str = "form.model.json") -> str:
    """The same run as one CLI command."""
    parts = [f"fillerai train {schema_path} {records_path}",
             f"--algorithm {options.algorithm}",
             f"-o {model_path}"]
    if options.seed is not None:
        parts.append(f"--seed {options.seed}")
    if options.holdout != 0.25:
        parts.append(f"--holdout {options.holdout}")
    if not options.use_rules:
        parts.append("--no-rules")
    if not options.learn_weights:
        parts.append("--no-learned-weights")
    for key, value in sorted(options.tuning.items()):
        parts.append(f"--set {key}={value}")
    parts.append("--verbose")
    return " \\\n    ".join(parts)


def script(options: TrainOptions, schema: FormSchema | None = None,
           schema_path: str = "form.schema.json",
           records_path: str = "records.json",
           model_path: str = "form.model.json",
           seeds: list[str] | None = None) -> str:
    """A runnable Python script that reproduces this training run."""
    algorithm = algos.get(options.algorithm)
    name = schema.name if schema else "the form"
    tuning = "\n".join(f"        {key!r}: {_literal(value)},"
                       for key, value in sorted(options.tuning.items()))
    tuning_block = f"    tuning={{\n{tuning}\n    }},\n" if options.tuning else ""
    seed_line = (f"    seed={options.seed},\n" if options.seed is not None
                 else "    # seed=42,  # pin this to get the same model every time\n")
    rules_line = "" if options.use_rules else "    use_rules=False,\n"
    weights_line = ("" if options.learn_weights
                    else "    learn_weights=False,\n")
    steps = "\n".join(f"#   {index}. {line}"
                      for index, line in enumerate(algorithm.recipe, start=1))
    chosen = ("\n".join(f"    {seed!r}," for seed in seeds)
              if seeds else "    # let the model choose, below")

    return f'''#!/usr/bin/env python3
"""Train an autofill model for {name}, using {algorithm.label}.

Generated by FillerAI. Everything below is the public API, so this script is
the run: change a number, run it again, and you have a different model.

What {algorithm.label} does, in order:
{steps}

Nothing here reaches the network and nothing installs: FillerAI is standard
library only, which is the point of it.
"""

import json
from pathlib import Path

from fillerai import extract_spec
from fillerai.train import TrainOptions, evaluate, suggest_seed_fields, train
from fillerai.train.trace import Trace

# ---------------------------------------------------------------- inputs

schema = extract_spec(Path({schema_path!r}))
records = json.loads(Path({records_path!r}).read_text(encoding="utf-8"))
if isinstance(records, dict):          # a dataset saved with its schema
    records = records["records"]

print(f"{{len(records)}} record(s), {{len(schema.fields)}} field(s) on the form")

# ---------------------------------------------------------------- training

# A quarter of the records are held back and never learned from. The
# confidence the model reports is measured on those, because a confidence
# fitted on the rows it describes is not a confidence.
options = TrainOptions(
    algorithm={options.algorithm!r},
    holdout={options.holdout},
{seed_line}{rules_line}{weights_line}{tuning_block})

# The trace is what the UI shows as live logs. Echoing it prints each stage
# as it happens, which on a wide form is the difference between watching it
# work and watching nothing.
watching = Trace(echo=True)
options.trace = watching

model = train(schema, records, options)

# ---------------------------------------------------------------- results

# The fields worth asking an agent to type first: the ones that, between
# them, unlock the most of the rest of the form.
seeds = [
{chosen}
]
seeds = seeds or suggest_seed_fields(model, 3)
print("ask the agent for:", ", ".join(seeds))

report = evaluate(model, records, seeds=seeds)
print(report.headline())

# Does the confidence mean anything? This is the table to read.
for band in report.reliability:
    if band["count"]:
        print(f"  said {{band['from']:.2f}}-{{band['to']:.2f}} -> "
              f"right {{band['accuracy'] * 100:5.1f}}% of {{band['count']}}")

Path({model_path!r}).write_text(model.to_json(), encoding="utf-8")
print("wrote {model_path}")
'''
